"""models_sync

Revision ID: 1c1b80fc8418
Revises: 48f326fcfef6
Create Date: 2026-02-26 15:49:51.255547

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '1c1b80fc8418'
down_revision: Union[str, None] = '48f326fcfef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
