"""create_core_tables

Revision ID: f0e91d5ef37b
Revises: 1c1b80fc8418
Create Date: 2026-02-26 16:34:33.561261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e91d5ef37b'
down_revision: Union[str, None] = '1c1b80fc8418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
